### PR TITLE
Need to propagate the action flag from the class to the template

### PR DESCRIPTION
**Pull request by yjarosz**
As the debian template, we should be able to modify the action flag from a hiera file.

### CODE REVIEW

**Comment by Trefex** [comment]
Would like to see this PR included asap 👍

**Comment by lelutin** [comment]
oops sorry for the wait. I'll try to review this tomorrow. simple change but I just want to see it within the rest of the code.

**Comment by lelutin** [comment]
This change makes total sense and it's fixing a feature that was missing for RHEL-type distros.

I've merged the one commit, and discarded the merge commit since it was useless.

Also: wow, there's a bunch of commits that have been accumulated since last release. It's now time to tag a new one and push this out to the forge :) I'll make a sign here when the release is done, before closing this PR

**Comment by yjarosz** [comment]
great :)

**Comment by lelutin** [comment]
blah! I was on the way to push version bump and tag 8 days ago when my laptop crashed. then there was a pull request which was closed and I've only had time to come back to this now.

but: version 1.3.0 released with your changes and others, too. thanks a bunch for your help!

**Pull request closed without merging**
