### PR TITLE
Change group to string

### PR DESCRIPTION
**Pull request by petems**
Fixes Puppet 4 Parser issue

### CODE REVIEW

**Comment by lelutin** [comment]
hey there, thanks for your contribution!

I didn't know puppet 4 enforced such a change since I haven't used it yet. I couldn't find anything in documentation that was showing this new requirement though... just out of curiosity, if you know of a documentation somewhere that shows this change, could you point it out to me?

Independantly, I'll try and reproduce this by installing puppet 4 in a VM and running this module with this version.

**Comment by lelutin** [comment]
I've just tried this with "puppet apply" by installing puppet-agent 4.3.1 and I didn't see it complaining about the group parameter being an integer. it applied the manifests correctly.

I'm trying to get some feedback from #puppet on irc to see if the server requires this change, but normally if the server requires something, puppet apply should shout to me about it..

**Comment by lelutin** [comment]
I didn't get much feedback but the one I got confirmed that integers were ok for the group parameter.

@petems you were saying in the commit message that this change was made to fix a parser issue with puppet 4. do you have an error message that you could paste here? and maybe some more info about the server (with which version are you getting an error, do you have some special settings wrt the parser)

**Comment by petems** [comment]
@lelutin Yeah, I just tested it myself and it didn't occur, I was testing out lots of different fail2ban modules from the forge so maybe I got confused. I did fix the test setup whilst testing this out, so I'll PR fixing the spec setup anyways :+1:

**Comment by lelutin** [comment]
@petems  ah-ha, ok thanks for the feedback then. if you end up using this module, feel free to submit other PRs if there's any bug or new feature that you want. I like getting contributions ;)

as for tests, I'm starting to play with rspec-puppet these days (yeah I know, late to the party) and it'd be great to have a set of unit tests at some point.

**Comment by petems** [comment]
@lelutin No problem!  Yeah, I just wanted a fail2ban module were I could set ignored IP's as a parameter, noe of the other fail2ban modules seemed to have that, bit suprising! :smiley:

**Pull request closed without merging**
